name: Release NPM Package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install

      - name: Run Lint and Test
        run: |
          set -e
          npm run lint
          npm run test

      - name: Integration Tests
        run: |
          npm link
          sleep 5; SLS_DEBUG=1 npm run test:integration

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
        run: npm publish
